### ISSUE TITLE
Stock management doesn't seems to work

### ISSUE THREAD

**Issue by Alex360hd** [OFFLINE-GmbH/oc-snipcartshop-plugin#21]
Hello,

I'm trying to play with stock management, but it seems that, whatever I try, I'm always able to order the product.

* Firstly : If you don't have variant, I don't see any stock field. Where do you set your stock for a simple product.
* Secondly : I tried to add some variant and set stock for each of them. Some option have quantity in stock, some options doesn't. I don't allow to purchase product that is out of stock. I also changed the Inventory mode option to select "Article variants". I'm still able to add product to the cart.
* Thirdly : Do you think the inventory management method field is required ? I would suppose that if you product have some variant, you need to be in article variants mode, and if not, normal mode. I think it can be deducted automatically.

So I don't understand how stock management works, could you please give me some help about this.

Thanks

Alex

**Comment by tobias-kuendig** [comment]
Thanks for your feedback. Stock management isn't completely implemented yet. 

1. Stock definitions on simple products are currently not implemented
1. You'll have to set the available stock via the Snipcart Backend since the stock isn't sent from October to Snipcart yet. 
1. Snipcart gives you the option to define stock on the product or on variants so it makes sense to provide this option to the user. I can imagine a use case where you create multiple variations of a product but you still want to limit the number of sold products independent of the sold variation. This is where the "stock by product" option may come in handy.

**Comment by Alex360hd** [comment]
Ok thank your for the answer. I don't want to the user the snipcart backoffice access to manage products and stock as your plugin already provide a very nice interface to manage all shop aspects (except customers maybe, hope it can be integrated later).

Ok for the third point, it make sense for that specific use case. Maybe it could be a nice addition to automatically select "Article Variants" in the dropdown as soon as you add a variant, and to select "Article" when there is no variant. The user would manually change that for the rare cases it's necessary, but it's a minor anot not urgent issue.

**Comment by tobias-kuendig** [comment]
Closed due to inactivity.
